.TH WMC 1 wmc\-VERSION
.SH NAME
wmc - window manager c
.SH SYNOPSIS
.B wmc {-s FILE | COMMAND}

COMMAND := help
.SH DESCRIPTION
Send EWMH and ICCCM signals to your window manager.
.SH OPTIONS
-s - a file to read commands from
.SH BUGS
Currently, this does not actually send any signals.
.SH AUTHOR
Created by Unsalted Baked Potato Chips (usbp@splattim.me)
